// Generated by CoffeeScript 1.9.1
var request;

request = require('superagent');

module.exports = function(exe, params) {
  var getparams;
  getparams = exe.build(params.__params);
  return function(cb) {
    return getparams(function(err, params) {
      if (err != null) {
        return cb(err);
      }
      return request.get(params).buffer().end(function(err, res) {
        if (err != null) {
          return cb(err);
        }
        if (!res.ok) {
          return cb(new Error(res.text));
        }
        return cb(null, res.text);
      });
    });
  };
};
