// Generated by CoffeeScript 1.9.2
var request, retryRequests;

request = require('superagent');

module.exports = {
  params: {
    http: function(exe, params) {
      var getsource;
      getsource = exe.build(params.__s);
      return function(cb) {
        return getsource(function(err, source) {
          var maxAttempts, parts, query, url;
          if (err != null) {
            return cb(err);
          }
          parts = source.split('?', 2);
          url = parts[0];
          query = parts[1] != null ? parts[1] : '';
          query = query.split('#')[0];
          maxAttempts = 1;
          if (maxAttempts == null) {
            maxAttempts = params.__p.attempts;
          }
          return retryRequests(url, query, maxAttempts, cb);
        });
      };
    }
  }
};

retryRequests = function(url, query, maxAttempts, cb) {
  var doRequest, errorMessage, nAttempts;
  nAttempts = 0;
  errorMessage = '';
  return (doRequest = function() {
    if (nAttempts > maxAttempts) {
      return cb(new Error("Max retries reached: " + url + "?" + query + "\n" + errorMessage));
    }
    return request.get(url).query(query).end((function() {
      return function(err, res) {
        nAttempts += 1;
        if (err || !res.ok) {
          if (errorMessage == null) {
            errorMessage = res.status;
          }
          if (errorMessage == null) {
            errorMessage = res.error.text;
          }
          if (errorMessage == null) {
            errorMessage = err.code;
          }
          return doRequest();
        }
        return cb(null, res.text);
      };
    })());
  })();
};
