// Generated by CoffeeScript 1.9.1
var request;

request = require('superagent');

module.exports = function(exe, params) {
  var getdata;
  getdata = exe.build(params.__source);
  return function(cb) {
    return getdata(function(err, data) {
      if (err != null) {
        return cb(err);
      }
      return request.get(data).buffer().end(function(err, res) {
        if (err != null) {
          return cb(err);
        }
        if (!res.ok) {
          return cb(new Error(res.text));
        }
        return cb(null, res.text);
      });
    });
  };
};
